### ISSUE TITLE
Last slice of last volume not used during evaluation

### ISSUE THREAD

**Issue by georgeyiasemis** [directgroup/direct#110]
**Describe the bug**
The last slice of the last volume is not being used during evaluation.

**To Reproduce**
Train model with any data and check logger of shape of last volume during evaluation.

**Expected behavior**
Use all slices.

**Additional context**

![image](https://user-images.githubusercontent.com/71031687/124435837-0dad2180-dd7e-11eb-8a84-c968ab53aa22.png)

**Comment by jonasteuwen** [comment]
This is fixed in #112
