### ISSUE TITLE
Extend reconstruction models beyond RIM

### ISSUE THREAD

**Issue by jonasteuwen** [directgroup/direct#47]
Goal of the library should be to also provide a reproducible baseline for the other MRI reconstruction models on public datasets. This should include, but is not limited to:
- Learned Primal Dual
- U-net postprocessing
- VNet

cc @wdika: any additions?

**Comment by wdika** [comment]
I think it would be nice if we also include non-machine learning methods and more than that categorize them between working in imspace and kspace. Specifically, having options for common Parallel Imaging techniques, such as
- Compressed Sensing (using a wavelet transform or Total Variation), SENSE (and maybe cg-SENSE) which work in imspace, and
- GRAPPA, (and maybe SAKE, LORAKS) which work in kspace. Also, RAKI is a machine learning approach for doing GRAPPA using a neural network.

For additional ML techniques I mention the

- KIKI‐net: cross‐domain convolutional neural networks for reconstructing undersampled magnetic resonance images, the
- MoDL: Model-Based Deep Learning Architecture for Inverse Problems, and the
- DAGAN: Deep De-Aliasing Generative Adversarial Networks for Fast Compressed Sensing MRI Reconstruction 

Definitely the ML methods @jonasteuwen mentioned can and should be the state-of-the-art for comparison and my abovementioned methods would basically extend the repo.

A **wrapper for BARToolbox** would be necessary not only for PI in imspace but also to offer options for sensitivities maps estimation with espirit and caldir.
