### ISSUE TITLE
Selection of the acceleration factor for evaluation

### ISSUE THREAD

**Issue by wdika** [directgroup/direct#8]
The accelerations argument should be parsed correctly to the [build_masking_function](https://github.com/directgroup/direct/blob/7fd133596bbb2b0694bf6005ca1065d2429918bf/tools/run_rim.py#L36)

For now, the acc factor will be selected automatically from the cfg file and set to the first option used for validation. 

Two ways to fix it:
1. Load it from the cfg file in a proper way and remove the argument
2. Parse the argument option and remove loading from the file

**Comment by jonasteuwen** [comment]
Thanks @wdika. Perhaps we can have a flag `--use-validation-settings` and if there are multiple sets just output multiple volumes? Otherwise command-line arguments are required. I think that might be a valuable solution?

**Comment by jonasteuwen** [comment]
I now made it possible to select the validation set, let's see how this goes. See https://github.com/directgroup/direct/commit/20ff3107c4a843fead190c075d3f9c4ad3126e6d

**Comment by jonasteuwen** [comment]
Will likely change this feature as the current version of DIRECT outputs the per-volume metrics of the real validation set. This would effectively make this irrelevant. Will close when the run script is removed, I want to rework the inference bit anyway.
