### ISSUE TITLE
Does not run with pytorch 1.8

### ISSUE THREAD

**Issue by jonasteuwen** [directgroup/direct#85]
Error is this: 

`INFO:RIMEngine:Cannot recover from exception aten::record_stream is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(None)`, call the op with an unnamed tensor, and set names on the result of the operation.. Exiting.`

**Comment by wdika** [comment]
Note for future solution.

Seems like torch.multiprocessing.spawn fails. It's still unclear if there is a mismatch between fork() and spawn() in the backend or DDP forward is called twice recursively. Meaning that the tensor on GPU 0 is unnamed but on GPU 1 still named.
